export const CHANGE_MODE = 'CHANGE_MODE';
export const SET_SAVED_QUOTE = 'SET_SAVED_QUOTE';

export const RESTORE_QUOTE_STATE = 'RESTORE_QUOTE_STATE';
export const ADD_QUOTE_ITEM = 'ADD_QUOTE_ITEM';
export const SELECT_EDIT_QUOTE_ITEM = 'SELECT_EDIT_QUOTE_ITEM';
export const SAVE_EDIT_QUOTE_ITEM = 'SAVE_EDIT_QUOTE_ITEM';
export const DELETE_QUOTE_ITEM = 'DELETE_QUOTE_ITEM';
export const RESET_QUOTE_STATE = 'RESET_QUOTE_STATE';
export const CANCEL_QUOTE = 'CANCEL_QUOTE';
